In [1]:
import requests
import pandas as pd
from pathlib import Path
from src import Scraper

sc = Scraper()

ROOT_PATH = Path("../").resolve()
DATASET_PATH = ROOT_PATH / "dataset"

In [2]:
df_venda = sc.sub_cem(local='maringa-pr',tipo='residencial', finalidade='venda', n_pages=585)

Coletando residencial (venda) em maringa-pr: 100%|██████████| 585/585 [23:00<00:00,  2.36s/it]

[OK] 11698 imóveis coletados em 585 páginas.

AttributeError: 'Scraper' object has no attribute 'local'

In [10]:
df_venda

,suites,rooms,dorms,bwc,parking_spaces,private_area,total_area,total,variation,apartment,...,royalty_value,latitude,longitude,address.complete,address.street,address.number,address.neighborhood,address.city,address.uf,address.complement
0,1,NaN,0,1,1,"21,71","54,00","169.000,00",0,307,...,0,-23.4094169,-51.9429957,"Rua Bragança, 43 - Zona 07, Maringá - PR",Rua Bragança,43,Zona 07,Maringá,PR,
1,0,NaN,2,1,1,"47,00","0,00","250.000,00",0,NaN,...,0,NaN,NaN,"Avenida Pioneiro Antonio Ruiz Saldanha, - Par...",Avenida Pioneiro Antonio Ruiz Saldanha,NaN,Parque Industrial,Maringá,PR,NaN
2,1,NaN,1,2,1,"53,50","103,00","288.574,34",0,NaN,...,1,-23.4154856,-51.9292466,"Rua Marechal Floriano Peixoto, 237, fundos - v...",Rua Marechal Floriano Peixoto,237,Zona 07,Maringá,PR,fundos - vista p/ catedral
3,0,NaN,2,1,1,"54,24","78,48","300.000,00",0,807,...,0,-23.4019932,-51.9303597,"Rua Olímpio Mendes da Rocha, 355 - Vila Espera...",Rua Olímpio Mendes da Rocha,355,Vila Esperança,Maringá,PR,
4,1,NaN,2,2,1,"68,71","88,75","309.000,00",0,12,...,0,-23.43525870420274,-51.925595052639764,"Rua Marciano Halchuk, 356, bloco g - Vila Bosq...",Rua Marciano Halchuk,356,Vila Bosque,Maringá,PR,bloco g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11692,3,NaN,0,0,0,"179,00","0,00","0,00",0,NaN,...,0,-23.4233437,-51.9270404,"Rua Neo Alves Martins, 1372, 01 - Zona 01 Cent...",Rua Neo Alves Martins,1372,Zona 01 Centro,Maringá,PR,01
11693,4,NaN,1,2,4,"250,00","0,00","0,00",0,NaN,...,0,-23.42570300,-51.94163500,"Avenida Tiradentes, 824 - Zona 01 Centro, Mari...",Avenida Tiradentes,824,Zona 01 Centro,Maringá,PR,
11694,1,NaN,2,2,0,"101,50","0,00","0,00",0,NaN,...,0,-23.428975,-51.9238073,"Rua Inhaúma, 603, 01 - Zona 03, Maringá - PR",Rua Inhaúma,603,Zona 03,Maringá,PR,01
11695,0,NaN,0,0,4,"245,00","437,21","0,00",0,NaN,...,0,-23.42357513627118,-51.942294123278806,"Avenida Xv de Novembro, 1012 - Zona 01 Centro,...",Avenida Xv de Novembro,1012,Zona 01 Centro,Maringá,PR,
11696,1,NaN,2,2,2,"119,00","0,00","0,00",0,NaN,...,0,-23.4205406,-51.9329875,"Avenida São Paulo, ., 111 - Zona 07, Maringá - PR",Avenida São Paulo,.,Zona 07,Maringá,PR,111

In [6]:
df_venda.to_csv("residencial-venda-maringa.csv")

In [3]:
pd.read_csv("residencial-venda-maringa.csv")

,Unnamed: 0,suites,rooms,dorms,bwc,parking_spaces,private_area,total_area,total,variation,...,royalty_value,latitude,longitude,address.complete,address.street,address.number,address.neighborhood,address.city,address.uf,address.complement
0,0,1,NaN,0,1,1,"21,71","54,00","169.000,00",0,...,0,-23.409417,-51.942996,"Rua Bragança, 43 - Zona 07, Maringá - PR",Rua Bragança,43,Zona 07,Maringá,PR,NaN
1,1,0,NaN,2,1,1,"47,00","0,00","250.000,00",0,...,0,NaN,NaN,"Avenida Pioneiro Antonio Ruiz Saldanha, - Par...",Avenida Pioneiro Antonio Ruiz Saldanha,NaN,Parque Industrial,Maringá,PR,NaN
2,2,1,NaN,1,2,1,"53,50","103,00","288.574,34",0,...,1,-23.415486,-51.929247,"Rua Marechal Floriano Peixoto, 237, fundos - v...",Rua Marechal Floriano Peixoto,237,Zona 07,Maringá,PR,fundos - vista p/ catedral
3,3,0,NaN,2,1,1,"54,24","78,48","300.000,00",0,...,0,-23.401993,-51.930360,"Rua Olímpio Mendes da Rocha, 355 - Vila Espera...",Rua Olímpio Mendes da Rocha,355,Vila Esperança,Maringá,PR,NaN
4,4,1,NaN,2,2,1,"68,71","88,75","309.000,00",0,...,0,-23.435259,-51.925595,"Rua Marciano Halchuk, 356, bloco g - Vila Bosq...",Rua Marciano Halchuk,356,Vila Bosque,Maringá,PR,bloco g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11692,11692,3,NaN,0,0,0,"179,00","0,00","0,00",0,...,0,-23.423344,-51.927040,"Rua Neo Alves Martins, 1372, 01 - Zona 01 Cent...",Rua Neo Alves Martins,1372,Zona 01 Centro,Maringá,PR,01
11693,11693,4,NaN,1,2,4,"250,00","0,00","0,00",0,...,0,-23.425703,-51.941635,"Avenida Tiradentes, 824 - Zona 01 Centro, Mari...",Avenida Tiradentes,824,Zona 01 Centro,Maringá,PR,NaN
11694,11694,1,NaN,2,2,0,"101,50","0,00","0,00",0,...,0,-23.428975,-51.923807,"Rua Inhaúma, 603, 01 - Zona 03, Maringá - PR",Rua Inhaúma,603,Zona 03,Maringá,PR,01
11695,11695,0,NaN,0,0,4,"245,00","437,21","0,00",0,...,0,-23.423575,-51.942294,"Avenida Xv de Novembro, 1012 - Zona 01 Centro,...",Avenida Xv de Novembro,1012,Zona 01 Centro,Maringá,PR,NaN
11696,11696,1,NaN,2,2,2,"119,00","0,00","0,00",0,...,0,-23.420541,-51.932988,"Avenida São Paulo, ., 111 - Zona 07, Maringá - PR",Avenida São Paulo,.,Zona 07,Maringá,PR,111

In [6]:
pd.read_csv("imoveis_maringa_venda_completo.csv")

,id,suites,rooms,dorms,bwc,parking_spaces,private_area,total_area,land_area,updated_days,...,advertiser.contacts.rental.whatsapp,advertiser.contacts.launch.email,advertiser.contacts.launch.phone,advertiser.contacts.launch.whatsapp,advertiser.addresses.season,advertiser.addresses.rental,advertiser.addresses.launch,advertiser.addresses.sale,condo.id,condo.name
0,c8188c6f-d068-408f-9dee-560e7f577534,1,NaN,0,1,1,"21,71","54,00","0,00",0,...,[{'id': 'ddd0cafb-3c75-4750-b14e-0197faea2d4d'...,[{'id': 'e8e1e775-e8d0-4dca-a2bb-366fa1484b25'...,[{'id': 'b5bcf4c6-386c-4a8c-9d4d-be5b1c39288d'...,[{'id': 'e91ca397-cff7-4b32-8a2a-1db9ee02f708'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",0429a7b4-203c-4a47-89e0-cba288c06704,Chaplin III
1,172a291d-c8e1-4b92-b9da-bf97c34bf0e1,0,NaN,2,1,1,"47,00","0,00","0,00",1,...,[{'id': '1b215233-9200-4d71-af1e-72a11da8939f'...,[{'id': '04116744-9d50-4575-ad37-47bd1ddc136a'...,[{'id': 'b6a02ec9-4b32-4dbb-8f69-5b24b124728a'...,[{'id': 'd187c87b-af1f-4391-b5b9-808c1a9a1566'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Lançamento', 'street': 'Aveni...","[{'department': 'Departamento de Vendas', 'str...",d609f8af-b09b-4b85-873c-b1c1f642faa7,Spazio Mirante do Parque
2,7f597aa6-de6c-4b6e-a1fa-206f5a8bbe28,1,NaN,1,2,1,"53,50","103,00","0,00",0,...,[{'id': 'ba50f7c1-dee4-463c-9986-9e9314e21a33'...,[{'id': '1b5b019c-e52b-4a60-a00e-a45ab616d1ad'...,[{'id': '9f9c728c-679c-4a47-9df7-e903a0ccc95c'...,[{'id': '53ab6c57-4466-4c9b-a6d1-86729c8c5dca'...,"[{'department': 'Temporada', 'street': 'Rua Pa...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Lançamento', 'street': 'Rua P...","[{'department': 'Departamento de Vendas', 'str...",8c4f2c2f-cc9c-4d56-8a5e-01b362ca47e0,Amélia Barão
3,ae718b27-aca2-4192-b88b-1e7adea61c31,0,NaN,2,1,1,"54,24","78,48","0,00",0,...,[{'id': '14502a78-ebf6-4a79-908e-66a90a3ff294'...,[{'id': 'd0b15bdc-7d28-4515-aef7-1ef38ced3d92'...,[{'id': '88de0b04-7a0b-4c57-8425-f23aa0f6b3bb'...,[{'id': '55e65280-5f32-4484-8428-586e98ee9a28'...,"[{'department': 'Temporada', 'street': 'Rua Vi...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",71567ad1-fc03-4c34-8470-e2eba041c33e,Residencial Martinelli
4,22abfebf-bd76-4afb-ad91-4992d3144dde,1,NaN,2,2,1,"68,71","88,75","0,00",0,...,[{'id': '11570dc5-ab7a-4c00-bf4f-f1bdb7c9642a'...,[{'id': '3965310e-06b0-4d21-996f-9e5b21ee8414'...,[{'id': '7f25ea4b-4707-4cd7-ba59-cac178bd7e27'...,[{'id': '4411c23c-29b1-484d-a8ef-0634628c0cbe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",fddbeb3d-906e-4a00-b990-350578686cdb,Guarita
5,ff4b63b9-994b-42a3-9503-7f2786db6c87,1,NaN,2,0,1,"85,00","0,00","0,00",1,...,[{'id': '29ba8ae7-655b-422d-b92a-832c00dd43a4'...,[{'id': '2a4e86cd-b19f-420b-902f-bd2a7fd5b3ae'...,[{'id': '0bc63c4d-fe58-427c-b146-c1e5a1a0dbb0'...,[{'id': '0f5ecc1b-4b50-4664-a331-4659329cfcab'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",7358ba31-006d-4d67-9b35-7e3ab4847bb0,Granville
6,007c2d64-8eb4-492c-8010-98da097f3f68,0,NaN,2,1,1,"49,00","60,00","60,00",0,...,[{'id': 'bd4022af-4b6b-4206-b603-16ddc45bf59b'...,[{'id': '3db73895-123d-465d-b017-48518797f5ef'...,[{'id': '94fd36e9-a912-4945-b659-758cd1133545'...,[{'id': 'ed03b5e0-ca67-4f32-a901-eb439a26e3fc'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento Lançamento', 'st...","[{'department': 'Departamento de Vendas', 'str...",3e4a2549-1ac2-4bcb-ba5f-bd0d2196ca76,Residencial Portal do Japão
7,7020c09a-9328-4fd7-9106-2f8b63d56f81,0,NaN,2,2,2,"0,00","114,00","183,00",0,...,[{'id': 'bd4022af-4b6b-4206-b603-16ddc45bf59b'...,[{'id': '3db73895-123d-465d-b017-48518797f5ef'...,[{'id': '94fd36e9-a912-4945-b659-758cd1133545'...,[{'id': 'ed03b5e0-ca67-4f32-a901-eb439a26e3fc'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento Lançamento', 'st...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
8,fe1bab09-8494-4334-85e2-febf6eb00c28,0,NaN,1,1,1,"32,00","68,00","68,00",0,...,[{'id': 'd57d2ac6-e393-491c-b2f8-e0407d993074'...,[{'id': '5e4a814b-56b8-45cd-bed2-13273a8625ad'...,[{'id': '0b1d9321-2acc-47ad-9c7d-cb972387cf91'...,[{'id': 'c324e03b-cf02-4a4d-ac5b-6ba2c5148cfe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Dep. Locação', 'street': 'Ave...","[{'department': 'Dep. Vendas', 'street': 'Aven...","[{'department': 'Dep. Vendas', 'street': 'Aven...",965bbed5-bc8a-44af-a172-6386aceed622,Unique Place
9,541811f7-19f9-40a0-9a2b-c178983d71d0,1,NaN,0,1,1,"52,38","68,21","0,00",0,...,[{'id': '0d444441-f9d7-4763-87da-f36046deb12c'...,[{'id': 'fd1249b8-533d-4da9-80b4-cd2b6a56c9c4'...,[{'id': '2d0fb7d5-257a-4cef-9d57-18ba1a8fd872'...,[{'id': 'ad210709-e230-4fd2-bb14-89997f735bab'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",403abbd3-025d-452c-a355-c14de44986f4,Residencial Soladio Itália II
10,52af2e20-2da0-4176-b255-ce63d3215930,0,NaN,2,1,1,"46,73","89,00","0,00",0,...,[{'id': '11570dc5-ab7a-4c00-bf4f-f1bdb7c9642a'...,[{'id': '3965310e-06b0-4d21-996f-9e5b21ee8414'...,[{'id': '7f25ea4b-4707-4cd7-ba59-cac178bd7e27'...,[{'id': '4411c23c-29b1-484d-a8ef-0634628c0cbe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",83ff3c84-a25a-47f5-b616-6b5f7f2c1dbd,Morro das Oliveiras
11,6bd4be05-4bd2-4f5b-a327-9669f7394435,0,NaN,2,1,1,"59,00","95,00","95,00",0,...,[{'id': 'b502d094-97ac-46c1-b149-a9fcba295f2e'...,[{'id': '448d5de3-01f6-4174-8feb-63d5fed05375'...,[{'id': '3d62ecda-c233-4074-9a7c-e9cf4d1a9c8a'...,[{'id': 'e7ff5e4f-9323-41ad-a767-15ae7f1faa83'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",e6fc03ef-9e7d-4172-bad7-6f3753907098,Residencial Maresias
12,a7450619-aba6-4e15-992a-3684ef64aad9,0,NaN,3,2,1,"74,69","108,02","0,00",0,...,[{'id': '11570dc5-ab7a-4c00-bf4f-f1bdb7c9642a'...,[{'id': '3965310e-06b0-4d21-996f-9e5b21ee8414'...,[{'id': '7f25ea4b-4707-4cd7-ba59-cac178bd7e27'...,[{'id': '4411c23c-29b1-484d-a8ef-0634628c0cbe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",c7c19933-9e1a-4780-be41-88400d2b8971,Mont Blanc
13,f10a4c28-642e-42de-b857-8b80c8e9119a,1,NaN,2,2,1,"0,00","78,64","150,00",0,...,[{'id': '11570dc5-ab7a-4c00-bf4f-f1bdb7c9642a'...,[{'id': '3965310e-06b0-4d21-996f-9e5b21ee8414'...,[{'id': '7f25ea4b-4707-4cd7-ba59-cac178bd7e27'...,[{'id': '4411c23c-29b1-484d-a8ef-0634628c0cbe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
14,a9f4e63f-c4b4-4c4d-bc6f-557adf080085,0,NaN,2,1,1,"55,00","0,00","0,00",0,...,[{'id': '54943f97-a24f-41d3-8b42-4ba85376ecce'...,[{'id': 'e461988e-4304-4a7d-aeb4-90b274da91c8'...,[{'id': '9a565e97-977b-4193-a205-fa82e300bcc8'...,[{'id': '08af3001-25f0-4f6a-8c7d-f54806a8f4ab'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
15,21eb4870-e171-497a-b785-a9b5a5785177,0,NaN,2,1,1,"55,17","104,40","0,00",0,...,[{'id': '0d444441-f9d7-4763-87da-f36046deb12c'...,[{'id': 'fd1249b8-533d-4da9-80b4-cd2b6a56c9c4'...,[{'id': '2d0fb7d5-257a-4cef-9d57-18ba1a8fd872'...,[{'id': 'ad210709-e230-4fd2-bb14-89997f735bab'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",d47aecdd-0490-4029-972d-efd741da3b43,Rouget Village
16,8e1a9a08-c6be-4388-8eb6-2f3fc5e6649d,1,NaN,1,2,1,"59,00","0,00","0,00",0,...,[{'id': '54943f97-a24f-41d3-8b42-4ba85376ecce'...,[{'id': 'e461988e-4304-4a7d-aeb4-90b274da91c8'...,[{'id': '9a565e97-977b-4193-a205-fa82e300bcc8'...,[{'id': '08af3001-25f0-4f6a-8c7d-f54806a8f4ab'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
17,9bb66129-e5d2-42c7-b72c-62f7fafaad31,1,NaN,2,2,2,"0,00","94,00","0,00",1,...,[{'id': '1b215233-9200-4d71-af1e-72a11da8939f'...,[{'id': '04116744-9d50-4575-ad37-47bd1ddc136a'...,[{'id': 'b6a02ec9-4b32-4dbb-8f69-5b24b124728a'...,[{'id': 'd187c87b-af1f-4391-b5b9-808c1a9a1566'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Lançamento', 'street': 'Aveni...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
18,b6ad34ff-fc76-4cfa-b7d6-519981ab4c2f,0,NaN,3,2,2,"0,00","120,00","0,00",1,...,[{'id': '1b215233-9200-4d71-af1e-72a11da8939f'...,[{'id': '04116744-9d50-4575-ad37-47bd1ddc136a'...,[{'id': 'b6a02ec9-4b32-4dbb-8f69-5b24b124728a'...,[{'id': 'd187c87b-af1f-4391-b5b9-808c1a9a1566'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Lançamento', 'street': 'Aveni...","[{'department': 'Departamento de Vendas', 'str...",NaN,NaN
19,005c59c3-a5bc-4ad7-82c2-6ee0502108fa,1,NaN,2,2,1,"108,24","154,38","0,00",0,...,[{'id': '11570dc5-ab7a-4c00-bf4f-f1bdb7c9642a'...,[{'id': '3965310e-06b0-4d21-996f-9e5b21ee8414'...,[{'id': '7f25ea4b-4707-4cd7-ba59-cac178bd7e27'...,[{'id': '4411c23c-29b1-484d-a8ef-0634628c0cbe'...,"[{'department': 'Temporada', 'street': 'Avenid...","[{'department': 'Departamento de Locação', 'st...","[{'department': 'Departamento de Vendas', 'str...","[{'department': 'Departamento de Vendas', 'str...",0809289c-9cd1-4f61-8053-38396b9a8f10,Ingá Parque

In [9]:
from datetime import datetime

'2026-03-02'